// ======= DO NOT EDIT THIS FILE ============
public class Radio
 {String owner;
  int volume,weight;
  Radio(String xOwner, int xVolume, int xWeight)
   {owner=xOwner;volume=xVolume;weight=xWeight;
   }
  public String toString()
   {return("(" + owner + "," + volume + "," + weight + ")");
   }
 }
