// ======= DO NOT EDIT THIS FILE ============
public class Land
 {String color;
  int area,peri;
  Land(String xColor, int xArea, int xPeri)
   {color=xColor;area=xArea;peri=xPeri;
   }
  public String toString()
   {return("(" + color + "," + area + "," + peri + ")");
   }
 }
